apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-amazing-cluster
  region: us-east-1
  version: "1.32"
  tags:
    Project: DevOpsWorkshop

nodeGroups:
  - name: general-ng
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: finalprojectesting-i
    labels:
      role: general
    tags:
      Environment: dev

  - name: compute-ng
    instanceType: t3.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 30
    ssh:
      allow: true
      publicKeyName: finalprojectesting-i
    labels:
      role: compute
    tags:
      Environment: dev

