apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
  namespace: ei-statuspage-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/ei-status_page
        ports:
        - containerPort: 8000
- name: Add Prometheus Helm repo
  run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update

- name: Install Prometheus (kube-prometheus-stack)
  run: |
    helm upgrade --install kube-prometheus prometheus-community/kube-prometheus-stack \
      --namespace monitoring --create-namespace


