apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage
  namespace: ei-statuspage-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      containers:
      - name: statuspage
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/ei-status_page:latest
        ports:
        - containerPort: 8000

