apiVersion: v1
kind: Service
metadata:
  name: statuspage
  namespace: itai-statuspage-db
  labels:
    app: statuspage
spec:
  selector:
    app: statuspage
  ports:
    - name: http
      port: 8000
      targetPort: 8000

