apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: statuspage-servicemonitor
  namespace: monitoring             
  labels:
    release: kube-prometheus        
spec:
  selector:
    matchLabels:
      app: statuspage               
  namespaceSelector:
    matchNames:
      - default          
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http

