apiVersion: v1
kind: Secret
metadata:
  name: status-page-secrets
type: Opaque
stringData:
  database_url: "postgresql://statuspage:yourpassword@postgres:5432/statuspage"
  redis_url: "redis://redis:6379/0"
  secret_key: "replace_with_generated_secret"
