replicaCount: 3

image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/ei-status_page
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: "status-page"
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "alb"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: status-page-ei.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 95

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables (to be injected under container env in deployment)
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: status-page-secrets
        key: database_url
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: status-page-secrets
        key: redis_url
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: status-page-secrets
        key: secret_key
