apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-postgres
  labels:
    app: statuspage-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage-postgres
  template:
    metadata:
      labels:
        app: statuspage-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: statuspage-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: statuspage-postgres
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.postgres.size }}
  storageClassName: {{ .Values.postgres.storageClass }}
