apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-page.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "status-page.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: statuspage-postgres

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-page.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "status-page.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: statuspage-redis
